<a href="https://colab.research.google.com/github/vijaya-123-bg/machine-learning-2/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy (Numerical Python) is a powerful open-source library in Python that is widely used for numerical computations. It provides support for multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. NumPy is the foundational package for scientific computing in Python, and many other libraries, like SciPy and Pandas, are built on top of it.

Key Features of NumPy:
Multi-dimensional Arrays: NumPy introduces the ndarray object, which allows you to create arrays of any dimension, such as 1D, 2D, or even higher-dimensional arrays.
Efficient Operations: It offers efficient operations on large arrays and matrices, which are implemented in C and Fortran, making them much faster than Python lists.
Mathematical Functions: NumPy includes a wide range of mathematical operations, such as element-wise addition, subtraction, multiplication, division, and more complex functions like trigonometric, statistical, and algebraic operations.
Broadcasting: This feature allows you to perform arithmetic operations on arrays of different shapes without explicitly reshaping them.
Linear Algebra Support: NumPy has built-in functions for performing linear algebra operations, such as matrix multiplication, inversion, eigenvalue calculation, etc.
Integration with Other Libraries: NumPy arrays are the standard data structure used in other scientific computing libraries, including Pandas (data analysis), Matplotlib (plotting), and TensorFlow (machine learning).

In [ ]:
import numpy as np

In [ ]:
## create array using numpy
##create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

In [ ]:
## 1 d array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)  ##1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

In [ ]:
np.arange(0,10,2)


array([0, 2, 4, 6, 8])

In [ ]:
np.arange(0,10,2).reshape(5,1)


In [ ]:
np.ones((3,4))


In [ ]:
## identity matrix
np.eye(4)

In [ ]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [ ]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [ ]:
## Universal Function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [ ]:
print(arr[0][0])
print(arr[0:2,2:])

In [ ]:
arr[1:,2:]


In [ ]:
## Modify array elements
arr[0,0]=100
print(arr)

In [ ]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [ ]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])